# Generated by Django 3.2 on 2022-01-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGodlango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns', models.CharField(max_length=500)),
                ('puerto', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Configuración de ámbito global',
                'verbose_name_plural': '*  Configuraciones de ámbito global',
            },
        ),
    ]
