# Generated by Django 3.2 on 2022-02-09 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apkaccess',
            options={'verbose_name': 'Acceso a APK', 'verbose_name_plural': 'Accesos a APK'},
        ),
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': 'Configuración', 'verbose_name_plural': 'Configuraciones'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='cfg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apk.configuration'),
        ),
    ]
