# Generated by Django 3.2 on 2022-02-11 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0002_auto_20220209_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apkaccess',
            name='cfg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apk.configuration'),
        ),
    ]
