# Generated by Django 3.2 on 2022-02-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Costo')),
                ('point_of_sale', models.CharField(max_length=900, verbose_name='Punto de venta')),
                ('hash', models.CharField(blank=True, default='asd', max_length=900, null=True, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Venta',
                'ordering': ['-date_creation'],
            },
        ),
    ]
