# Generated by Django 3.2 on 2022-02-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='hash',
            field=models.CharField(blank=True, max_length=900, null=True, unique=True),
        ),
    ]
