# Generated by Django 3.2 on 2022-02-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_sale_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['date_creation'], 'verbose_name': 'Venta'},
        ),
    ]
